---
- name: Install nodejs
  hosts: all
  tasks:
    - name: Install nvm
      git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v0.33.11

    - name: Source nvm in ~/.{{ item }}
      lineinfile: >
        dest=~/.{{ item }}
        line="source ~/.nvm/nvm.sh"
        create=yes
      with_items:
        - bashrc
        - profile

    - name: Install node and set version
      shell: "source ~/.nvm/nvm.sh && nvm install --lts"
      args:
        executable: /bin/bash
